version: '3'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /opt/data/mongo_home:/data/db
    restart: always

  backend:
    # use make realize to build a new images of realize
    image: realize:${REALIZE_VERSION}
    hostname: backend
    ports:
      - "8080:8080"
      - "8082:8082"
      - "443:443"
    environment:
      - GO111MODULE=on
      # LOGGING
      - LOG_FORMAT=${LOG_FORMAT}
      # HTTP
      - HTTP_READ_TIMEOUT=${HTTP_READ_TIMEOUT}
      - HTTP_WRITE_TIMEOUT=${HTTP_WRITE_TIMEOUT}
      - HTTP_READ_HEADER_TIMEOUT=${HTTP_READ_HEADER_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      - PORT=${PORT}
      - HTTP_HOST=${HTTP_HOST}
      - HTTP_ALLOWED_ORIGINS=${HTTP_ALLOWED_ORIGINS}
      - HTTP_PORT=${HTTP_PORT}
      - HTTP_TLS_CERT_FILE=${HTTP_TLS_CERT_FILE}
      - HTTP_TLS_KEY_FILE=${HTTP_TLS_KEY_FILE}
      # DB
      - MONGODB_ADDRS=${MONGODB_ADDRS}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_TIMEOUT=${MONGODB_TIMEOUT}
      # POLICY
      - CASBIN_MONGODB_ADDRS=${CASBIN_MONGODB_ADDRS}
      - CASBIN_MONGODB_DATABASE=${CASBIN_MONGODB_DATABASE}
      - CASBIN_MONGODB_USERNAME=${CASBIN_MONGODB_USERNAME}
      - CASBIN_MONGODB_PASSWORD=${CASBIN_MONGODB_PASSWORD}
      - CASBIN_MONGODB_TIMEOUT=${CASBIN_MONGODB_TIMEOUT}
      # OAUTH
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      # CLOUDINARY
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      # SMTP
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_DEFAULT_FROM=${SMTP_DEFAULT_FROM}
    volumes:
      - ../../.realize.yaml:/go/src/github.com/pthethanh/robusta/.realize.yaml
      - ../../main.go:/go/src/github.com/pthethanh/robusta/main.go
      - ../../go.mod:/go/src/github.com/pthethanh/robusta/go.mod
      - ../../go.sum:/go/src/github.com/pthethanh/robusta/go.sum
      - ../../internal:/go/src/github.com/pthethanh/robusta/internal/
      - ../../web/dist:/go/src/github.com/pthethanh/robusta/web/dist
      - ../../configs:/go/src/github.com/pthethanh/robusta/configs
      - ../scripts:/scripts
      - ../certs:/certs
    working_dir: /go/src/github.com/pthethanh/robusta
    entrypoint: [ "sh", "-c", "/scripts/wait-for.sh mongodb:27017 --timeout=5 -- realize start" ]
    depends_on:
      - mongodb
    restart: always

  frontend:
    image: node:11.10.0-alpine
    hostname: frontend
    ports:
      - "8081:8081"
    environment:
      - BASE_API=http://backend:8088
    volumes:
      - ../../web:/home/robusta
    working_dir: /home/robusta/
    command: [ sh, -c, "npm rebuild node-sass && npm run serve" ]
    depends_on:
      - backend
    restart: always
