version: '3'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      # You can replace /opt/data/mongo_home by any path to
      # a directory on your machine.
      # MongoDB will use that directory to store all the data.
      - /opt/data/mongo_home:/data/db
    restart: always

  backend:
    # use make realize to build a new images of realize
    image: realize:${REALIZE_VERSION}
    hostname: backend
    ports:
      - "8080:8080"
      - "8082:8082"
      - "443:443"
    environment:
      # Add more environments here if you want to pass it
      # to backend service env config.
      - MONGODB_ADDRS=mongodb:27017
      - ALLOWED_ORIGINS=*
      - GOOGLE_CLIENT_ID=511091284450-9oes9tddrskgtlfcafblrke7pk28lthp.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=xxx
      - GOOGLE_REDIRECT_URL=http://mylocalhost.com/auth/google/callback
      - SESSION_SECRET=xxx
      - CASBIN_MONGODB_ADDRS=mongodb:27017
      - GO111MODULE=on
      - CLOUDINARY_SECRET=xxx
      - CLOUDINARY_API_KEY=xxx
      - CLOUDINARY_CLOUD_NAME=pthethanh
      # db
      - MONGODB_ADDRS=ds121871.mlab.com:21871
      - MONGODB_DATABASE=goway
      - MONGODB_USERNAME=goway
      - MONGODB_PASSWORD=xxx
      - MONGODB_TIMEOUT=10s
      # casbin
      - CASBIN_MONGODB_ADDRS=ds121871.mlab.com:21871
      - CASBIN_MONGODB_DATABASE=goway
      - CASBIN_MONGODB_USERNAME=goway
      - CASBIN_MONGODB_PASSWORD=xxx
      - CASBIN_MONGODB_TIMEOUT=10s
      # http server
      - HTTP_PORT=8080
      - HTTP_HOST=https://goway.herokuapp.com
      #- HTTP_PORT=443
      #- HTTP_TLS_CERT_FILE=/certs/server.pem
      #- HTTP_TLS_KEY_FILE=/certs/server-key.pem
      # email
      - SMTP_ADDRESS=smtp.gmail.com:587
      - SMTP_USERNAME=gowaynotification@gmail.com
      - SMTP_PASSWORD=xxx
      - SMTP_DEFAULT_FROM=gowaynotification@gmail.com
    volumes:
      # Add Go packages here if needed.
      - ../../.realize.yaml:/go/src/github.com/pthethanh/robusta/.realize.yaml
      - ../../main.go:/go/src/github.com/pthethanh/robusta/main.go
      - ../../go.mod:/go/src/github.com/pthethanh/robusta/go.mod
      - ../../go.sum:/go/src/github.com/pthethanh/robusta/go.sum
      - ../../internal:/go/src/github.com/pthethanh/robusta/internal/
      - ../../web/dist:/go/src/github.com/pthethanh/robusta/web/dist
      - ../../configs:/go/src/github.com/pthethanh/robusta/configs
      - ../scripts:/scripts
      - ../certs:/certs
    working_dir: /go/src/github.com/pthethanh/robusta
    entrypoint: [ "sh", "-c", "/scripts/wait-for.sh mongodb:27017 --timeout=5 -- realize start" ]
    depends_on:
      - mongodb
    restart: always

  frontend:
    image: node:11.10.0-alpine
    hostname: frontend
    ports:
      - "8081:8081"
    environment:
      - BASE_API=http://backend:8088
    volumes:
      - ../../web:/home/robusta
    working_dir: /home/robusta/
    command: [ sh, -c, "npm rebuild node-sass && npm run serve" ]
    depends_on:
      - backend
    restart: always
